/** SVG 属性名 → React / JSX 属性名 映射（渲染与代码生成共用） */

export const ATTR_MAP: Record<string, string> = {
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-opacity': 'strokeOpacity',
  'fill-opacity': 'fillOpacity',
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'clip-path': 'clipPath',
  'font-family': 'fontFamily',
  'font-size': 'fontSize',
  'font-weight': 'fontWeight',
  'font-style': 'fontStyle',
  'text-anchor': 'textAnchor',
  'letter-spacing': 'letterSpacing',
  'word-spacing': 'wordSpacing',
  'text-decoration': 'textDecoration',
  'dominant-baseline': 'dominantBaseline',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  gradientunits: 'gradientUnits',
  gradienttransform: 'gradientTransform',
  spreadmethod: 'spreadMethod',
  patternunits: 'patternUnits',
  patterntransform: 'patternTransform',
  patterncontentunits: 'patternContentUnits',
  'marker-start': 'markerStart',
  'marker-mid': 'markerMid',
  'marker-end': 'markerEnd',
  preserveaspectratio: 'preserveAspectRatio',
  'vector-effect': 'vectorEffect',
  'paint-order': 'paintOrder',
  'shape-rendering': 'shapeRendering',
  'baseline-shift': 'baselineShift',
  'flood-color': 'floodColor',
  'flood-opacity': 'floodOpacity',
  stddeviation: 'stdDeviation',
  'color-interpolation-filters': 'colorInterpolationFilters',
  'xlink:href': 'xlinkHref',
  refx: 'refX',
  refy: 'refY',
  markerwidth: 'markerWidth',
  markerheight: 'markerHeight',
  markerunits: 'markerUnits',
  clippathunits: 'clipPathUnits',
  maskunits: 'maskUnits',
  filterunits: 'filterUnits',
  primitiveunits: 'primitiveUnits',
  attributename: 'attributeName',
  repeatcount: 'repeatCount',
  keytimes: 'keyTimes',
  keysplines: 'keySplines',
  calcmode: 'calcMode',
  'xml:space': 'xmlSpace',
};

/** 只能作为 CSS 使用的属性 */
export const CSS_ONLY = new Set(['mix-blend-mode', 'isolation', 'filter']);

export function camel(k: string): string {
  return k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
